name: Desplegament a EC2 amb GHCR

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Descàrrega del codi font
        uses: actions/checkout@v4

      - name: Passar nom del repositori a minúscules
        id: string
        run: |
          echo "repo_lowercase=${GITHUB_REPOSITORY,,}" >> ${GITHUB_OUTPUT}

      - name: Login al registre GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir i publicar imatge Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.string.outputs.repo_lowercase }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Passar nom del repositori a minúscules per al deploy
        id: string_deploy
        run: |
          echo "repo_lowercase=${GITHUB_REPOSITORY,,}" >> ${GITHUB_OUTPUT}

      - name: Desplegar la imatge via SSH a AWS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            export IMAGE=ghcr.io/${{ steps.string_deploy.outputs.repo_lowercase }}:latest
            export PORT=80
            cd ~/taskmanager
            docker compose -f docker-compose.yml up -d --pull always --no-build